import {api} from './auth.js';
import {t,translate,locale} from './i18n.js';
const $=id=>document.getElementById(id);let users=[],tracks=[],selected='',busy=false;
const run=async action=>{if(busy)return;busy=true;const controls=[...document.querySelectorAll('main button,main input,main select')].filter(control=>!control.closest('[data-pane=audio],[data-pane=twitch],[data-pane=master],[data-pane=updater]'));controls.forEach(control=>control.disabled=true);try{$('admin-message').textContent='';await action();}catch(error){$('admin-message').textContent=error.message;}finally{busy=false;controls.forEach(control=>control.disabled=false);}};
function select(user){selected=user?.id||'';$('user-name').value=user?.username||'';$('user-role').value=user?.role||'operator';$('user-password').value='';$('user-password').required=!selected;$('user-delete').hidden=!selected;$('user-heading').textContent=t(selected?'adminEditUser':'adminNewUser');}
function renderUsers(){const list=$('users-list');list.replaceChildren();for(const user of users){const row=document.createElement('div');row.className='portal-user';const title=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small'),edit=document.createElement('button');strong.textContent=user.username;small.textContent=t(user.role==='admin'?'authAdministrator':'authOperator')+(user.mustChangePassword?' · '+t('authPasswordPending'):'');title.append(strong,small);edit.textContent=t('portalEdit');edit.addEventListener('click',()=>select(user));row.append(title,edit);list.append(row);}}
function renderRatings(){ $('rating-search').placeholder=t('adminSearch');const filter=$('rating-search').value.toLowerCase(),sort=$('rating-sort').value;const filtered=tracks.filter(row=>[row.title,row.artist,row.album].join(' ').toLowerCase().includes(filter)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):b[sort]-a[sort]||b.count-a.count);const body=$('rating-rows');body.replaceChildren();for(const row of filtered){const tr=document.createElement('tr'),track=document.createElement('td'),artist=document.createElement('small'),album=document.createElement('td'),average=document.createElement('td'),votes=document.createElement('td'),distribution=document.createElement('div');track.textContent=row.title;artist.textContent=row.artist;track.append(artist);album.textContent=row.album;average.textContent=row.average.toLocaleString(locale(),{maximumFractionDigits:2})+' / 5';distribution.className='rating-distribution';for(let i=0;i<5;i++){const part=document.createElement('span');part.textContent=(i+1)+'★ '+row.distribution[i];distribution.append(part);}average.append(distribution);const details=document.createElement('button');details.textContent=row.count+' · '+t('viewerShowVotes');details.addEventListener('click',()=>showRatingViewers(row));votes.append(details);tr.append(track,album,average,votes);body.append(tr);}$('ratings-empty').hidden=filtered.length>0;}
async function loadRatings(){tracks=(await api('/api/admin/ratings')).tracks;renderRatings();}
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(tab=>tab.setAttribute('aria-selected',String(tab===button)));document.querySelectorAll('[data-pane]').forEach(pane=>pane.hidden=pane.dataset.pane!==button.dataset.tab);history.replaceState(null,'','#'+button.dataset.tab);}));
$('user-new').addEventListener('click',()=>select());
$('user-form').addEventListener('submit',event=>{event.preventDefault();run(async()=>{users=(await api('/api/admin/users',{action:'save',id:selected,username:$('user-name').value,role:$('user-role').value,password:$('user-password').value})).users;select();renderUsers();$('admin-message').textContent=t('portalSaved');});});
$('user-delete').addEventListener('click',()=>{if(confirm(t('adminDeleteConfirm')))run(async()=>{users=(await api('/api/admin/users',{action:'delete',id:selected})).users;select();renderUsers();});});
$('rating-search').addEventListener('input',renderRatings);$('rating-sort').addEventListener('change',renderRatings);$('rating-refresh').addEventListener('click',()=>run(loadRatings));
$('rotate-overlays').addEventListener('click',()=>{if(confirm(t('adminRotateConfirm')))run(async()=>{await api('/api/admin/broadcast',{});$('admin-message').textContent=t('adminRotated');});});
window.addEventListener('languagechange',()=>{translate();renderUsers();renderRatings();$('user-heading').textContent=t(selected?'adminEditUser':'adminNewUser');});
translate();select();await run(async()=>{users=(await api('/api/admin/users')).users;renderUsers();await loadRatings();});

function selectTab(){const tab=location.hash.slice(1);[...document.querySelectorAll('[data-tab]')].find(button=>button.dataset.tab===tab)?.click();}window.addEventListener('hashchange',selectTab);selectTab();

let viewerDialogRequest=0;
async function showRatingViewers(track){const request=++viewerDialogRequest,dialog=$('rating-viewers-dialog');$('rating-viewers-title').textContent=track.title+' · '+t('adminVotes');$('rating-viewers-list').replaceChildren();$('rating-viewers-message').textContent=t('viewerLoading');dialog.showModal();try{const result=await api('/api/admin/ratings/'+encodeURIComponent(track.id)+'/viewers');if(request!==viewerDialogRequest||!dialog.open)return;$('rating-viewers-message').textContent=result.legacyCount?t('viewerLegacy',{count:result.legacyCount}):'';for(const row of result.viewers.sort((a,b)=>a.login.localeCompare(b.login))){const item=document.createElement('li');item.textContent=row.login+' — '+row.stars+' / 5 ★';$('rating-viewers-list').append(item);}}catch(error){if(request===viewerDialogRequest)$('rating-viewers-message').textContent=error.message;}}
$('rating-viewers-dialog').addEventListener('close',()=>++viewerDialogRequest);
