import {api} from './auth.js';
import {t,translate} from './i18n.js';
import {boundedText} from './creative-options.js';
const limit=8*1024*1024;
export async function listMedia(){return (await api('/api/media')).media;}
export const commonsUrl=value=>{try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='upload.wikimedia.org'&&!u.username&&!u.password?u.href:null;}catch{return null;}};
const plain=value=>new DOMParser().parseFromString(String(value||''),'text/html').body.textContent.slice(0,1800);
export async function searchCommons(query,gifs=false){
 const params=new URLSearchParams({action:'query',format:'json',origin:'*',generator:'search',gsrnamespace:'6',gsrsearch:query+(gifs?' filetype:bitmap filemime:image/gif':' filetype:bitmap'),gsrlimit:'8',prop:'imageinfo',iiprop:'url|size|mime|extmetadata',iiurlwidth:'240',iiextmetadatafilter:'Artist|LicenseShortName|Credit|Attribution'});
 const response=await fetch('https://commons.wikimedia.org/w/api.php?'+params,{credentials:'omit',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error(t('mediaSearchFailed'));const data=await response.json();if(data.error)throw Error(t('mediaSearchFailed'));
 return Object.values(data.query?.pages||{}).map(page=>{const info=page.imageinfo?.[0],meta=info?.extmetadata||{};if(!info||!commonsUrl(info.url)||!['image/png','image/jpeg','image/gif','image/webp'].includes(info.mime)||info.size>limit||info.width>4096||info.height>4096)return null;return {name:page.title.replace(/^File:/,''),url:commonsUrl(info.url),thumbnail:commonsUrl(info.thumburl)||commonsUrl(info.url),source:'https://commons.wikimedia.org/wiki/'+encodeURIComponent(page.title),credit:[plain(meta.Artist?.value),plain(meta.LicenseShortName?.value),plain(meta.Credit?.value),plain(meta.Attribution?.value)].filter(Boolean).join(' · ').slice(0,2000),size:info.size};}).filter(Boolean);
}
async function boundedBlob(response){if(!response.ok||Number(response.headers.get('Content-Length'))>limit)throw Error(t('mediaInvalid'));const reader=response.body.getReader(),parts=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>limit)throw Error(t('mediaInvalid'));parts.push(value);}return new Blob(parts);}finally{await reader.cancel().catch(()=>{});}}
async function upload(blob,name,credit='',source=''){if(blob.size>limit)throw Error(t('mediaInvalid'));const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});return api('/api/media',{action:'upload',name:boundedText(name,160),data,credit:boundedText(credit,2000),source});}
export function setupMedia(root,onSelect,onRefresh=()=>{}){
 root.innerHTML='<h2 data-i18n="mediaHeading"></h2><p data-i18n="mediaHelp"></p><label for="media-upload" data-i18n="mediaUpload"></label><input id="media-upload" type="file" accept="image/png,image/jpeg,image/gif,image/webp"><div id="media-list" class="media-grid"></div><details><summary data-i18n="mediaCommons"></summary><p data-i18n="mediaCommonsHelp"></p><input id="media-query" maxlength="160" data-i18n-aria="mediaSearch"><label><input id="media-gifs" type="checkbox"> GIF</label><button id="media-search" type="button" data-i18n="mediaSearch"></button><div id="media-results" class="media-grid"></div></details><p id="media-message" role="status"></p>';
 const $=id=>root.querySelector('#'+id);let busy=false,records=[];
 async function run(action){if(busy)return;busy=true;root.querySelectorAll('button,input').forEach(e=>e.disabled=true);$('media-message').textContent=t('mediaWorking');try{await action();$('media-message').textContent='';}catch(error){$('media-message').textContent=error.message;}finally{busy=false;root.querySelectorAll('button,input').forEach(e=>e.disabled=false);}}
 const card=(record,url)=>{const node=document.createElement('article'),img=document.createElement('img'),name=document.createElement('p');img.src=url;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';name.textContent=record.name;node.append(img,name);if(record.credit){const credit=document.createElement('small');credit.textContent=record.credit;node.append(credit);}if(record.source?.startsWith('https://commons.wikimedia.org/wiki/')){const link=document.createElement('a');link.href=record.source;link.target='_blank';link.rel='noopener noreferrer';link.textContent=t('mediaSource');node.append(link);}return node;};
 function render(){const list=$('media-list');list.replaceChildren();for(const record of records){const node=card(record,'/api/media/'+record.id),choose=document.createElement('button'),remove=document.createElement('button');choose.textContent=t('mediaUse');choose.addEventListener('click',()=>onSelect(record));remove.textContent=t('portalDelete');remove.addEventListener('click',()=>{if(confirm(t('mediaDeleteConfirm')))run(async()=>{await api('/api/media',{action:'delete',id:record.id});await reload();});});node.append(choose,remove);list.append(node);}}
 async function reload(){records=await listMedia();render();onRefresh(records);}
 $('media-upload').addEventListener('change',()=>run(async()=>{const file=$('media-upload').files[0];if(!file)return;const result=await upload(file,file.name);await reload();onSelect(result);$('media-upload').value='';}));
 $('media-search').addEventListener('click',()=>run(async()=>{const query=$('media-query').value.trim();if(!query)return;const rows=await searchCommons(query,$('media-gifs').checked);$('media-results').replaceChildren();if(!rows.length)$('media-results').textContent=t('mediaNoResults');for(const row of rows){const node=card(row,row.thumbnail),button=document.createElement('button');button.textContent=t('mediaImport');button.addEventListener('click',()=>run(async()=>{const response=await fetch(row.url,{credentials:'omit',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(15000)});if(!commonsUrl(response.url))throw Error(t('mediaInvalid'));const result=await upload(await boundedBlob(response),row.name,row.credit,row.source);await reload();onSelect(result);}));node.append(button);$('media-results').append(node);}}));
 window.addEventListener('languagechange',()=>{translate(root);render();});translate(root);run(reload);
}
